---
apiVersion: v1
kind: Service
metadata:
  name: listen-app-service
  labels:
    app: listen-app
spec:
  type: NodePort
  selector:
    app: listen-app
  ports:
  - protocol: TCP
    port: 6702
    targetPort: 6702
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listen-app-deployment
spec:
  selector:
    matchLabels:
      app: listen-app
  replicas: 1
  template:
    metadata:
      labels:
        app: listen-app
    spec:
      containers:
      - name: listenapp
        image: narendra8686/listen-app-img:latest
        ports:
        - containerPort: 6702